export const countriesMock = [
  {
    name: {
      common: 'Malta',
      official: 'Republic of Malta',
      nativeName: {
        eng: { official: 'Republic of Malta', common: 'Malta' },
        mlt: { official: "Repubblika ta ' Malta", common: 'Malta' },
      },
    },
    tld: ['.mt'],
    cca2: 'MT',
    ccn3: '470',
    cca3: 'MLT',
    cioc: 'MLT',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { EUR: { name: 'Euro', symbol: '€' } },
    idd: { root: '+3', suffixes: ['56'] },
    capital: ['Valletta'],
    altSpellings: ['MT', 'Republic of Malta', "Repubblika ta' Malta"],
    region: 'Europe',
    subregion: 'Southern Europe',
    languages: { eng: 'English', mlt: 'Maltese' },
    translations: {
      ara: { official: 'جمهورية مالطا', common: 'مالطا' },
      bre: { official: 'Republik Malta', common: 'Malta' },
      ces: { official: 'Maltská republika', common: 'Malta' },
      cym: { official: 'Republic of Malta', common: 'Malta' },
      deu: { official: 'Republik Malta', common: 'Malta' },
      est: { official: 'Malta Vabariik', common: 'Malta' },
      fin: { official: 'Maltan tasavalta', common: 'Malta' },
      fra: { official: 'République de Malte', common: 'Malte' },
      hrv: { official: 'Republika Malta', common: 'Malta' },
      hun: { official: 'Máltai Köztársaság', common: 'Málta' },
      ita: { official: 'Repubblica di Malta', common: 'Malta' },
      jpn: { official: 'マルタ共和国', common: 'マルタ' },
      kor: { official: '몰타 공화국', common: '몰타' },
      nld: { official: 'Republiek Malta', common: 'Malta' },
      per: { official: 'جمهوری مالت', common: 'مالت' },
      pol: { official: 'Republika Malty', common: 'Malta' },
      por: { official: 'República de Malta', common: 'Malta' },
      rus: { official: 'Республика Мальта', common: 'Мальта' },
      slk: { official: 'Maltská republika', common: 'Malta' },
      spa: { official: 'República de Malta', common: 'Malta' },
      swe: { official: 'Republiken Malta', common: 'Malta' },
      tur: { official: 'Malta Cumhuriyeti', common: 'Malta' },
      urd: { official: 'جمہوریہ مالٹا', common: 'مالٹا' },
      zho: { official: '马耳他共和国', common: '马耳他' },
    },
    latlng: [35.83333333, 14.58333333],
    landlocked: false,
    area: 316.0,
    demonyms: {
      eng: { f: 'Maltese', m: 'Maltese' },
      fra: { f: 'Maltaise', m: 'Maltais' },
    },
    flag: '\uD83C\uDDF2\uD83C\uDDF9',
    maps: {
      googleMaps: 'https://goo.gl/maps/skXCqguxDxxEKVk47',
      openStreetMaps: 'https://www.openstreetmap.org/relation/365307',
    },
    population: 525285,
    gini: { 2018: 28.7 },
    fifa: 'MLT',
    car: { signs: ['M'], side: 'left' },
    timezones: ['UTC+01:00'],
    continents: ['Europe'],
    flags: {
      png: 'https://flagcdn.com/w320/mt.png',
      svg: 'https://flagcdn.com/mt.svg',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/mt.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/mt.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [35.88, 14.5] },
    postalCode: { format: '@@@ ###|@@@ ##', regex: '^([A-Z]{3}\\d{2}\\d?)$' },
  },
  {
    name: {
      common: 'Belgium',
      official: 'Kingdom of Belgium',
      nativeName: {
        deu: { official: 'Königreich Belgien', common: 'Belgien' },
        fra: { official: 'Royaume de Belgique', common: 'Belgique' },
        nld: { official: 'Koninkrijk België', common: 'België' },
      },
    },
    tld: ['.be'],
    cca2: 'BE',
    ccn3: '056',
    cca3: 'BEL',
    cioc: 'BEL',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { EUR: { name: 'Euro', symbol: '€' } },
    idd: { root: '+3', suffixes: ['2'] },
    capital: ['Brussels'],
    altSpellings: [
      'BE',
      'België',
      'Belgie',
      'Belgien',
      'Belgique',
      'Kingdom of Belgium',
      'Koninkrijk België',
      'Royaume de Belgique',
      'Königreich Belgien',
    ],
    region: 'Europe',
    subregion: 'Western Europe',
    languages: { deu: 'German', fra: 'French', nld: 'Dutch' },
    translations: {
      ara: { official: 'مملكة بلجيكا', common: 'بلجيكا' },
      bre: { official: 'Rouantelezh Belgia', common: 'Belgia' },
      ces: { official: 'Belgické království', common: 'Belgie' },
      cym: { official: 'Teyrnas Gwlad Belg', common: 'Gwlad Belg' },
      deu: { official: 'Königreich Belgien', common: 'Belgien' },
      est: { official: 'Belgia Kuningriik', common: 'Belgia' },
      fin: { official: 'Belgian kuningaskunta', common: 'Belgia' },
      fra: { official: 'Royaume de Belgique', common: 'Belgique' },
      hrv: { official: 'Kraljevina Belgija', common: 'Belgija' },
      hun: { official: 'Belga Királyság', common: 'Belgium' },
      ita: { official: 'Regno del Belgio', common: 'Belgio' },
      jpn: { official: 'ベルギー王国', common: 'ベルギー' },
      kor: { official: '벨기에 왕국', common: '벨기에' },
      nld: { official: 'Koninkrijk België', common: 'België' },
      per: { official: 'پادشاهی بلژیک', common: 'بلژیک' },
      pol: { official: 'Królestwo Belgii', common: 'Belgia' },
      por: { official: 'Reino da Bélgica', common: 'Bélgica' },
      rus: { official: 'Королевство Бельгия', common: 'Бельгия' },
      slk: { official: 'Belgické kráľovstvo', common: 'Belgicko' },
      spa: { official: 'Reino de Bélgica', common: 'Bélgica' },
      swe: { official: 'Konungariket Belgien', common: 'Belgien' },
      tur: { official: 'Belçika Krallığı', common: 'Belçika' },
      urd: { official: 'مملکتِ بلجئیم', common: 'بلجئیم' },
      zho: { official: '比利时王国', common: '比利时' },
    },
    latlng: [50.83333333, 4.0],
    landlocked: false,
    borders: ['FRA', 'DEU', 'LUX', 'NLD'],
    area: 30528.0,
    demonyms: {
      eng: { f: 'Belgian', m: 'Belgian' },
      fra: { f: 'Belge', m: 'Belge' },
    },
    flag: '\uD83C\uDDE7\uD83C\uDDEA',
    maps: {
      googleMaps: 'https://goo.gl/maps/UQQzat85TCtPRXAL8',
      openStreetMaps: 'https://www.openstreetmap.org/relation/52411',
    },
    population: 11555997,
    gini: { 2018: 27.2 },
    fifa: 'BEL',
    car: { signs: ['B'], side: 'right' },
    timezones: ['UTC+01:00'],
    continents: ['Europe'],
    flags: {
      png: 'https://flagcdn.com/w320/be.png',
      svg: 'https://flagcdn.com/be.svg',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/be.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/be.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [50.83, 4.33] },
    postalCode: { format: '####', regex: '^(\\d{4})$' },
  },
  {
    name: {
      common: 'Brazil',
      official: 'Federative Republic of Brazil',
      nativeName: {
        por: { official: 'República Federativa do Brasil', common: 'Brasil' },
      },
    },
    tld: ['.br'],
    cca2: 'BR',
    ccn3: '076',
    cca3: 'BRA',
    cioc: 'BRA',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { BRL: { name: 'Brazilian real', symbol: 'R$' } },
    idd: { root: '+5', suffixes: ['5'] },
    capital: ['Brasília'],
    altSpellings: [
      'BR',
      'Brasil',
      'Federative Republic of Brazil',
      'República Federativa do Brasil',
    ],
    region: 'Americas',
    subregion: 'South America',
    languages: { por: 'Portuguese' },
    translations: {
      ara: { official: 'جمهورية البرازيل الاتحادية', common: 'البرازيل' },
      bre: { official: 'Republik Kevreel Brazil', common: 'Brazil' },
      ces: { official: 'Brazilská federativní republika', common: 'Brazílie' },
      cym: { official: 'Gweriniaeth Ffederal Brasil', common: 'Brasil' },
      deu: { official: 'Föderative Republik Brasilien', common: 'Brasilien' },
      est: { official: 'Brasiilia Liitvabariik', common: 'Brasiilia' },
      fin: { official: 'Brasilian liittotasavalta', common: 'Brasilia' },
      fra: { official: 'République fédérative du Brésil', common: 'Brésil' },
      hrv: { official: 'Savezne Republike Brazil', common: 'Brazil' },
      hun: { official: 'Brazil Szövetségi Köztársaság', common: 'Brazília' },
      ita: { official: 'Repubblica federativa del Brasile', common: 'Brasile' },
      jpn: { official: 'ブラジル連邦共和国', common: 'ブラジル' },
      kor: { official: '브라질 연방 공화국', common: '브라질' },
      nld: { official: 'Federale Republiek Brazilië', common: 'Brazilië' },
      per: { official: 'جمهوری فدراتیو برزیل', common: 'برزیل' },
      pol: { official: 'Federacyjna Republika Brazylii', common: 'Brazylia' },
      por: { official: 'República Federativa do Brasil', common: 'Brasil' },
      rus: { official: 'Федеративная Республика Бразилия', common: 'Бразилия' },
      slk: { official: 'Brazílska federatívna republika', common: 'Brazília' },
      spa: { official: 'República Federativa del Brasil', common: 'Brasil' },
      swe: { official: 'Förbundsrepubliken Brasilien', common: 'Brasilien' },
      tur: { official: 'Brezilya Federal Cumhuriyeti', common: 'Brezilya' },
      urd: { official: 'وفاقی جمہوریہ برازیل', common: 'برازیل' },
      zho: { official: '巴西联邦共和国', common: '巴西' },
    },
    latlng: [-10.0, -55.0],
    landlocked: false,
    borders: [
      'ARG',
      'BOL',
      'COL',
      'GUF',
      'GUY',
      'PRY',
      'PER',
      'SUR',
      'URY',
      'VEN',
    ],
    area: 8515767.0,
    demonyms: {
      eng: { f: 'Brazilian', m: 'Brazilian' },
      fra: { f: 'Brésilienne', m: 'Brésilien' },
    },
    flag: '\uD83C\uDDE7\uD83C\uDDF7',
    maps: {
      googleMaps: 'https://goo.gl/maps/waCKk21HeeqFzkNC9',
      openStreetMaps: 'https://www.openstreetmap.org/relation/59470',
    },
    population: 212559409,
    gini: { 2019: 53.4 },
    fifa: 'BRA',
    car: { signs: ['BR'], side: 'right' },
    timezones: ['UTC-05:00', 'UTC-04:00', 'UTC-03:00', 'UTC-02:00'],
    continents: ['South America'],
    flags: {
      png: 'https://flagcdn.com/w320/br.png',
      svg: 'https://flagcdn.com/br.svg',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/br.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/br.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [-15.79, -47.88] },
    postalCode: { format: '#####-###', regex: '^(\\d{8})$' },
  },
  {
    name: {
      common: 'Hungary',
      official: 'Hungary',
      nativeName: { hun: { official: 'Magyarország', common: 'Magyarország' } },
    },
    tld: ['.hu'],
    cca2: 'HU',
    ccn3: '348',
    cca3: 'HUN',
    cioc: 'HUN',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: { HUF: { name: 'Hungarian forint', symbol: 'Ft' } },
    idd: { root: '+3', suffixes: ['6'] },
    capital: ['Budapest'],
    altSpellings: ['HU'],
    region: 'Europe',
    subregion: 'Central Europe',
    languages: { hun: 'Hungarian' },
    translations: {
      ara: { official: 'الجمهورية المجرية', common: 'المجر' },
      bre: { official: 'Hungaria', common: 'Hungaria' },
      ces: { official: 'Maďarsko', common: 'Maďarsko' },
      cym: { official: 'Hungary', common: 'Hungary' },
      deu: { official: 'Ungarn', common: 'Ungarn' },
      est: { official: 'Ungari', common: 'Ungari' },
      fin: { official: 'Unkari', common: 'Unkari' },
      fra: { official: 'Hongrie', common: 'Hongrie' },
      hrv: { official: 'Madžarska', common: 'Mađarska' },
      hun: { official: 'Magyarország', common: 'Magyarország' },
      ita: { official: 'Ungheria', common: 'Ungheria' },
      jpn: { official: 'ハンガリー', common: 'ハンガリー' },
      kor: { official: '헝가리', common: '헝가리' },
      nld: { official: 'Hongarije', common: 'Hongarije' },
      per: { official: 'مجارستان', common: 'مجارستان' },
      pol: { official: 'Węgry', common: 'Węgry' },
      por: { official: 'Hungria', common: 'Hungria' },
      rus: { official: 'Венгрия', common: 'Венгрия' },
      slk: { official: 'Maďarsko', common: 'Maďarsko' },
      spa: { official: 'Hungría', common: 'Hungría' },
      swe: { official: 'Ungern', common: 'Ungern' },
      tur: { official: 'Macaristan', common: 'Macaristan' },
      urd: { official: 'مجارستان', common: 'مجارستان' },
      zho: { official: '匈牙利', common: '匈牙利' },
    },
    latlng: [47.0, 20.0],
    landlocked: true,
    borders: ['AUT', 'HRV', 'ROU', 'SRB', 'SVK', 'SVN', 'UKR'],
    area: 93028.0,
    demonyms: {
      eng: { f: 'Hungarian', m: 'Hungarian' },
      fra: { f: 'Hongroise', m: 'Hongrois' },
    },
    flag: '\uD83C\uDDED\uD83C\uDDFA',
    maps: {
      googleMaps: 'https://goo.gl/maps/9gfPupm5bffixiFJ6',
      openStreetMaps: 'https://www.openstreetmap.org/relation/21335',
    },
    population: 9749763,
    gini: { 2018: 29.6 },
    fifa: 'HUN',
    car: { signs: ['H'], side: 'right' },
    timezones: ['UTC+01:00'],
    continents: ['Europe'],
    flags: {
      png: 'https://flagcdn.com/w320/hu.png',
      svg: 'https://flagcdn.com/hu.svg',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/hu.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/hu.svg',
    },
    startOfWeek: 'monday',
    capitalInfo: { latlng: [47.5, 19.08] },
    postalCode: { format: '####', regex: '^(\\d{4})$' },
  },
];

export const teste = {};
